version: "3"

services:
    web:
        build: ./Web
        volumes:
            - ./Web:/Web
            - ./logs:/Web/logs
        depends_on:
            - server
        environment:
            - TZ=Asia/Shanghai

    server:
        restart: always
        build: ./Server
        expose:
            - "8000"
        volumes:
            - ./Server:/Server
            - ./logs:/Server/logs
        environment:
            - TZ=Asia/Shanghai

    nginx:
        image: nginx
        restart: always
        ports:
            - "8800:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./Server/static:/Server/static
            - ./Web/dist:/Web/dist
            - ./logs:/logs
        depends_on:
            - web
        environment:
            - TZ=Asia/Shanghai
